tree1="""
    <html>
    <body>
        <div>
            1
            <p>
                1.1
                <a>1.1.1</a>
                <a>1.1.2</a>
            </p>
            <p>
                1.2
                <a>1.2.1</a>
                <a>1.2.2</a>
            </p>
            <p>
                1.3
                <a>1.3.1</a>
            </p>
        </div>
        <div>
            2
            <p>
                2.1
                <div>
                    2.1.1
                </div>
            </p>
        </div>
        <div>
            3
            <p>
                3.1
                <div>
                    3.1.1
                </div>
            </p>
        </div>
        <div>
            4
            <p>
                4.1
                <div>
                    4.1.1
                </div>
            </p>
        </div>
    </body>
    </html>
"""
tree2="""
    <html>
    <body>
        <div>
            1
            <p>
                1.1
                <a>1.1.1</a>
                <a>1.1.2</a>
            </p>
            <p>
                1.2
                <a>1.2.1</a>
                <a>1.2.2</a>
            </p>
            <p>
                1.3
                <a>1.3.1</a>
            </p>
        </div>
        <div>
            2
            <p>
                2.1
                <div>
                    2.1.1
                </div>
            </p>
        </div>
        <div>
            <a>2/2</a>
        </div>
        <div>
            3
            <p>
                3.1
                <div>
                    3.1.1
                </div>
            </p>
        </div>
        <div>
            <a>3/3</a>
        </div>
        <div>
            4
            <p>
                4.1
                <div>
                    4.1.1
                </div>
            </p>
        </div>
        <div>
            <a>4/4</a>
        </div>
        <div>
            <table><tr><td></td></tr></table>
        </div>
        <div>
            5
            <p>
                5.1
                <div>
                    5.1.1
                </div>
            </p>
        </div>
        <div>
            <a>5/5</a>
        </div>
        <div>
            6
            <p>
                6.1
                <div>
                    6.1.1
                </div>
            </p>
        </div>
        <div>
            <a>6/6</a>
        </div>
        <div>
            7
            <p>
                7.1
                <div>
                    7.1.1
                </div>
            </p>
        </div>
        <div>
            <a>7/7</a>
        </div>
    </body>
    </html>
"""
tree3="""
    <html>
    <body>
        <div>
            2
            <p>
                2.1
                <div>
                    2.1.1
                </div>
            </p>
        </div>
        <div>
            <a>2/2</a>
        </div>
        <div>
            3
            <p>
                3.1
                <div>
                    3.1.1
                </div>
            </p>
        </div>
        <div>
            <a>3/3</a>
        </div>
        <div>
            4
            <p>
                4.1
                <div>
                    4.1.1
                </div>
            </p>
        </div>
        <div>
            1
            <p>
                1.1
                <a>1.1.1</a>
                <a>1.1.2</a>
            </p>
            <p>
                1.2
                <a>1.2.1</a>
                <a>1.2.2</a>
            </p>
            <p>
                1.3
                <a>1.3.1</a>
            </p>
            <div>
                <table><tr><td></td></tr></table>
            </div>
            <div>
                5
                <p>
                    5.1
                    <div>
                        5.1.1
                    </div>
                </p>
            </div>
            <div>
                <a>5/5</a>
            </div>
            <div>
                6
                <p>
                    6.1
                    <div>
                        6.1.1
                    </div>
                </p>
            </div>
            <div>
                <a>6/6</a>
            </div>
            <div>
                7
                <p>
                    7.1
                    <div>
                        7.1.1
                    </div>
                </p>
            </div>
            <div>
                <a>7/7</a>
            </div>
        </div>
        <div>
            <a>4/4</a>
        </div>
    </body>
    </html>
"""
